name: CD to Hugging Face Spaces

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0


      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          HF_SPACE="spaces/ymcaPrabhu/Emotion-Detection-App"
          git remote add space "https://huggingface.co/${HF_SPACE}" || true
          git push "https://TOKEN:${HF_TOKEN}@huggingface.co/${HF_SPACE}" HEAD:main --force

      - name: Show Space URL
        run: echo "Deployed: https://huggingface.co/spaces/ymcaPrabhu/My-First"
